---
# SSH接続ポート
## 推測されにくく、他のアプリケーションポートと重複しないポートを指定する
## 開発段階では、22番を含む複数ポートを指定しておくと安全
ssh_ports:
  - 22
  - 1022

# 外部からのアクセスを許可するポート
accept_ports:
  # httpポート
  - port: 80
    protocol: 'tcp'
  
  # httpsポート
  - port: 443
    protocol: 'tcp'
