- hosts: all # イベントリファイルに記述されたすべてのホストに対して実行
  become: true # sudo権限で実行
  tasks: # 各タスク定義｜nameは任意項目だが、分かりやすい名前をつけておくと管理しやすい
    - name: add a new user
      # Linuxユーザの作成
      ## userモジュール｜name=<ユーザ名> state=<present|absent> uid=<ユーザID>
      ### present: 存在する状態（存在しない場合は作成）, absent: 存在しない状態（存在する場合は削除）
      ### uidは指定しなくとも良いが、複数サーバでユーザIDを統一するためには指定しておく必要がある
      user: name=testuser state=present uid=1001

    - name: mkdir .ssh
      # .sshフォルダの作成
      ## fileモジュール｜path=<ファイルパス> state=<file|directory|...> owner=<所有者> group=<所有グループ> mode=<パーミッション>
      ### パーミッションは8進数で指定しなければならないため 0700 や '700' などのように指定すること
      file: path=/home/testuser/.ssh/ state=directory owner=testuser group=testuser mode=0700

    - name: generate ssh key
      # SSH鍵ペアの生成
      ## userモジュール｜generate_ssh_key=yes: SSH鍵ペアを生成
      ### => /home/testuser/.ssh/ に id_rsa（秘密鍵）, id_rsa.pub（公開鍵）生成
      user: name=testuser generate_ssh_key=yes
    
    - name: download ssh-key
      # SSH鍵のダウンロード
      ## fetchモジュール｜src=<サーバ内のファイルパス> dest=<ローカルの保存先パス> flat=<no|yes>
      ### flat=noだと、srcで指定したパスをまるごと保存してしまうため、yesを指定してファイル名のみでファイルを保存するようにする
      fetch: src=/home/testuser/.ssh/id_rsa dest=./ssh/testuser-id_rsa flat=yes
