all:
  hosts: # ホスト定義
    vagrant: # vagrant host
      ansible_host: 172.17.8.100 # 指定サーバのIPアドレス
  vars:  # 変数定義（接続設定）
    ansible_ssh_port: 22 # SSH接続ポートは通常 22番
    ansible_ssh_user: vagrant # SSH接続ユーザ名
    ansible_ssh_private_key_file: ./.vagrant/machines/default/virtualbox/private_key # SSH秘密鍵
    ansible_sudo_pass: vagrant # rootユーザパスワード
