# -*- mode: ruby -*-
# vi: set ft=ruby :

ssh_port = 22 # ssh接続ポート

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vbguest.auto_update = false # host-guest間の差分アップデートを無効化

  # 仮想マシの private IPアドレス設定
  config.vm.network "private_network", ip: "172.17.8.200"

  # ssh接続ポート設定
  config.ssh.guest_port = ssh_port
  config.vm.network "forwarded_port", guest: ssh_port, host: 22222, id: "ssh"
end
