---
- name: pyenvインストールに必要なパッケージのインストール
  yum:
    name:
      - gcc
      - gcc-c++
      - make
      - git
      - openssl-devel
      - bzip2-devel
      - zlib-devel
    state: present

- name: git clone pyenv
  git: repo=git://github.com/pyenv/pyenv.git dest=/usr/local/src/pyenv accept_hostkey=yes force=yes

- name: pyenvのprofile作成
  template: src=../templates/pyenv.j2 dest=/etc/profile.d/pyenv.sh

- name: pyenvで使用するpythonバージョンをインストール＆既定に設定
  # bash をログインシェルとして起動してコマンドを実行させる
  ## シェル起動時に /etc/profile.d/pyenv.sh を反映するため pyenvコマンドを使用可能にすることができる
  ## pyenv install -s: skip if already installed
  shell: /bin/bash -lc "pyenv install -s {{ python_version }} && pyenv global {{ python_version }}"

- name: 管理者ユーザがsudoなしでpyenv実行できるように変更
  file:
    path: /usr/local/src/pyenv/
    owner: root
    group: '{{ admin_group }}'
    mode: 0775
    recurse: true
