---
# ユーザ設定
## ユーザを追加・削除する場合はここを変更する

# 管理者ユーザ: sshログイン & sudo権限あり
admin_users:
  - name: 'centos-admin'
    uid: 1001 # 重複しないユーザIDを指定すること

# 一般ユーザ: sftp接続のみ可
users:
  - name: 'centos-user'
    uid: 2001

# ---

# ユーザグループ設定
## 基本的に編集しない
admin_group: 'admin'
user_group: 'devel'

# sftp専用ユーザのルートディレクトリ
## 指定ディレクトリより上位のディレクトリにはアクセスできなくなる
chroot_dir: '/var/www'

# sftpで編集可能にするディレクトリ
## chroot_dir 直下にマウントされる
sftp_editable_dir: '/var/devel/httpdocs'

# ---

# サーバ再起動待ちのタイムアウト時間 [秒]
## Vagrant環境だと実際には reboot が起こらないため、短めのタイムアウト時間を指定した方が良い
## Docker環境の場合は手動でDockerコンテナを再起動する必要があるため、基本的に再起動が必要な操作は行わないようにする
## 通常のサーバであれば、それなりに長いタイムアウト時間を指定する必要がある
reboot_wait_timeout: 10
