---
# 各グループ名は group_vars/***/, playbooks/***.yml と統一する
management: # 共通セキュリティ設定グループ
  hosts: # ホスト定義
    web: # ホスト名は基本的に web で統一する
      ansible_host: centos # 接続先サーバのIPアドレス or ドメイン名
      ansible_ssh_port: 22 # SSH接続ポートは通常 22番
      ansible_ssh_user: root # SSH接続ユーザ名
      ansible_ssh_pass: root # SSH接続パスワード
      ansible_sudo_pass: root # rootユーザパスワード
pyenv: # Python環境整備グループ
  hosts:
    web:
      ansible_host: centos
      ansible_ssh_port: 22
      ansible_ssh_user: root
      ansible_ssh_pass: root
      ansible_sudo_pass: root
docker: # dockerインストールグループ
  hosts:
    web:
      ansible_host: centos
      ansible_ssh_port: 22
      ansible_ssh_user: root
      ansible_ssh_pass: root
      ansible_sudo_pass: root
