---
# 管理者ユーザ設定
## includeモジュールで 別ファイルの中身をそのまま展開できる
- include: admin_users.yml

# 一般ユーザ設定
- include: users.yml

- name: sshd設定
  # Jinja2テンプレートエンジンを利用してテンプレートファイルを展開してアップロード
  # templateモジュール｜src=<テンプレートファイル> dest=<アップロード先ファイルパス> ...
  ## テンプレートファイル内では {{変数名}} で変数を展開できる（詳しくは Jinja2 公式リファレンス参照）
  template: src=../templates/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0600

- name: sshd再起動
  # serviceモジュール｜name=<サービス名> state=<reloaded|restarted|started|stopped> ...
  service:
    name: sshd
    state: restarted
