---
# SELinux無効化設定
## includeモジュールで 別ファイルの中身をそのまま展開できる
- include: selinux_disabled.yml

# 管理者ユーザ設定
- include: admin_users.yml

# 一般ユーザ設定
- include: users.yml

# sshd, iptables設定
- include: services.yml
